package tn.talan.entity.postgresql;
// Generated 15 ao�t 2016 00:21:09 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.time.LocalDateTime;

/**
 * StatCollectDevice generated by hbm2java
 */
@Embeddable
public class StatCollectDeviceId implements java.io.Serializable {

    @Column(name = "dc")
    private String dc;
    @Column(name = "device")
    private String device;
    @Column(name = "date_collect")
    private LocalDateTime DateCollect;
    @Column(name = "task_id")
    private String taskId;

    public String getDc() {
        return dc;
    }

    public void setDc(String dc) {
        this.dc = dc;
    }

    public String getDevice() {
        return device;
    }

    public void setDevice(String device) {
        this.device = device;
    }

    public LocalDateTime getDateCollect() {
        return DateCollect;
    }

    public void setDateCollect(LocalDateTime dateCollect) {
        DateCollect = dateCollect;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((DateCollect == null) ? 0 : DateCollect.hashCode());
        result = prime * result + ((dc == null) ? 0 : dc.hashCode());
        result = prime * result + ((device == null) ? 0 : device.hashCode());
        result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        StatCollectDeviceId other = (StatCollectDeviceId) obj;
        if (DateCollect == null) {
            if (other.DateCollect != null)
                return false;
        } else if (!DateCollect.equals(other.DateCollect))
            return false;
        if (dc == null) {
            if (other.dc != null)
                return false;
        } else if (!dc.equals(other.dc))
            return false;
        if (device == null) {
            if (other.device != null)
                return false;
        } else if (!device.equals(other.device))
            return false;
        if (taskId == null) {
            if (other.taskId != null)
                return false;
        } else if (!taskId.equals(other.taskId))
            return false;
        return true;
    }

}
